[locallog]
max_channel_size = "100"
filename = "log/qasearch.log"
level = "7"

# goose配置
# [GooseBuild]和[GooseSearch]是框架所需要的配置信息
# 策略自定义的配置

[GooseBuild]
# 建库最多使用cpu个数.0表示设置为机器的cpu数
MaxProcs = 0

    # 建库数据库的相关配置
    [GooseBuild.DataBase]
    # 索引库的目标位置
    DbPath = "data/index"
    # 正排转倒排的内存缓冲区最大容纳term数量.
    # 越大越好,减少读写磁盘数,随之内存占用越多.
    TransformMaxTermCnt = 10000000
    # 索引库最大id数
    MaxId = 5000000
    # 索引文件最大文件大小,单位(B),1G = 1073741824B
    MaxIndexFileSize = 1073741824
    # Data文件最大文件大小,单位(B),1G = 1073741824B
    MaxDataFileSize = 1073741824
    # 每个doc的Value大小,单位(B)
    ValueSize = 1

[GooseSearch]
# 检索最多使用cpu个数.0表示设置为机器的cpu数
MaxProcs = 0

    # 检索相关配置
    [GooseSearch.Search]
    # 检索服务端口
    BindAddr = "10.10.139.235:10033"
    
    # 定时刷新相关配置
    [GooseSearch.Refresh]
    # 每隔多少秒刷新一次
    SleepTime = 10


[Strategy]

# 调权参数的权重
ValueBoost = [0.0]


    # 建库策略
    [Strategy.Indexer]
        # 切词词典
        [Strategy.Indexer.Scws]
        xdbdict = "dict/dict.utf8.xdb"
        rules = "dict/rules.utf8.ini"

        # 赋权相关
        [Strategy.Indexer.Weight]
        titleBoost = 1.0
        KeyWordBoost = 0.8
    
    # 检索策略
    [Strategy.Searcher]
        # 切词词典
        [Strategy.Searcher.Scws]
        xdbdict = "dict/dict.utf8.xdb"
        rules = "dict/rules.utf8.ini"

        # 专名词典
        [Strategy.Searcher.TrieDict]
        # 先加载DictFile,如果加载失败,则读取DataFile转化为DictFile
        DataFile = "dict/name.txt"
        DictFile = "dict/name.dict"
